config/routes.rb
Flashcards::Application.routes.draw do
  root "pages#home"
  devise_for :users

  resources :cards
  resources :stats, only: [:create, :show, :index]

  resources :quiz_sessions, only: [:create, :show]

  post 'answer', to: 'quiz_sessions#answer'
  get 'unfinished', to: 'quiz_sessions#unfinished'

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
end

app/models/card.rb
class Card < ActiveRecord::Base
  has_many :terms, :inverse_of => :card
  accepts_nested_attributes_for :terms
  validates :terms, :definition, :category, :object_type, :example, :return_type, presence: true

  def self.object_types
    order("object_type").pluck("distinct object_type")
  end

  def self.categories
    select("category").collect(&:category).uniq.try(:sort) || []
  end

  def self.category_object_types(category)
    where(category: category).pluck(:object_type).uniq
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :quiz_session
  belongs_to :user
  belongs_to :card

  validates :user_id, :card_id, :quiz_session_id, presence: true
end

app/models/quiz_session.rb
class QuizSession < ActiveRecord::Base
  has_many :questions
  belongs_to :user

  validates_presence_of :user_id, :object_type, :category

  after_create :create_questions

  def cards
    Card.where(category: category, object_type: object_type)
  end

  def finished?
    unanswered.length < 1
  end

  def get_question
    unanswered.sample
  end

  def unanswered
    questions.map{ |q| q if q.correct.nil? }.compact
  end

  private

  def create_questions
    cards.each do |card|
      questions << Question.new(card: card, user: user )
    end
  end
end

app/models/quiz_session_question.rb
class QuizSessionQuestion < ActiveRecord::Base
  belongs_to :quiz_session
  belongs_to :user
  belongs_to :card

  validates :user_id, :card_id, :quiz_session_id, presence: true
end

app/models/stats.rb
class Stats < ActiveRecord::Base
  belongs_to :quiz_session
  belongs_to :user

  validates :user_id, :card_id, :quiz_session_id, presence: true
end

app/models/term.rb
class Term < ActiveRecord::Base
  belongs_to :card
  validates :term, :card, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  validates :email, presence: true
  has_many :quiz_sessions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  protect_from_forgery except: :create
  before_action :has_access?
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render action: 'show', status: :created, location: @card }
      else
        format.html { render action: 'new' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:definition, :object_type, :example, :return_type, :category, terms_attributes: [:term])
    end

    def has_access?
      redirect_to new_user_session_path unless current_user && current_user[:email] == ENV['ADMIN_EMAIL']
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_filter :authenticate_user!

  def home
    @user = current_user
    @category = Card.categories
    @object_type = Card.object_types
  end
end

app/controllers/quiz_sessions_controller.rb
class QuizSessionsController < ApplicationController

  before_filter :authenticate_user!

  def create
    quiz_type = params[:object_type]
    quiz_category = params[:category]
    quiz_session = QuizSession.create(user_id: current_user.id, category: quiz_category, object_type: quiz_type)

    if quiz_session.persisted?
      redirect_to quiz_session_url(quiz_session)
    else
      redirect_to root_url, alert: "There was a problem."
    end
  end

  def show
    @quiz_session = QuizSession.where(id: params[:id], user: current_user).first
    if @quiz_session.finished?
      redirect_to stat_path(@quiz_session)
    else
      @card = @quiz_session.get_question.card
    end
  end

  def answer
    submitted_answer = strip_whitespace(params[:submitted_answer].downcase)

    quiz_session = QuizSession.where(id: params[:id], user: current_user).first
    question_record = quiz_session.questions.where(card_id: params[:card], user: current_user).first

    if correct_answer?(submitted_answer)
      question_record.update!(answer: submitted_answer, correct: true)
      redirect_to quiz_session_url(quiz_session), alert: "That was correct."
    else
      question_record.update!(answer: submitted_answer, correct: false)
      redirect_to quiz_session_url(quiz_session), alert: "That was incorrect. The correct answer was #{possible_answers.join(" or ")}."
    end
  end

  def unfinished
    @unfinished_quizzes ||= QuizSession.where(user: current_user).collect{ |qs| qs if !qs.finished? }.compact
    @total_quiz_count = QuizSession.where(user: current_user).count
    if @total_quiz_count >= 1
      @unfinished_percentage = ((@unfinished_quizzes.count.to_f / @total_quiz_count.to_f) * 100).round
      @finished_percentage = 100 - @unfinished_percentage
    end
  end

  private

  def possible_answers
    Card.where(id: params[:card]).first.terms.map { |term| strip_whitespace(term.term.downcase) }
  end

  def strip_whitespace(dirty_answer)
    dirty_answer.gsub(/\s+/, "")
  end

  def correct_answer?(submitted_answer)
    possible_answers.each do |answer|
      return true if submitted_answer == answer
    end
    false
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController

  def index
    @past_quizzes = QuizSession.where(user: current_user).order(created_at: :desc)
  end

  def show
    @quiz_session = QuizSession.where(id: params[:id], user: current_user).first
    @correct = @quiz_session.questions.where(correct: true).count
    @question_total = @quiz_session.questions.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def local_display_date(timestamp)
    timestamp.strftime("%a %b #{timestamp.day.ordinalize},%l:%M %p")
  end
end

app/views/cards/_form.html.haml
= form_for @card do |f|
  - if @card.errors.any?
    #error_explanation
      %h2= "#{pluralize(@card.errors.count, "error")} prohibited this card from being saved:"
      %ul
        - @card.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :category
    = f.text_field :category, value: Card.last.try(:category)
  .field
    = f.label :object_type
    = f.text_field :object_type, value: Card.last.try(:object_type)
  .field#termgroup
    = f.label :terms
    = f.fields_for :terms do |term|
      = term.text_field :term
  %button#add_term + Term
  .field
    = f.label :return_type
    = f.text_field :return_type
  .field
    = f.label :definition
    = f.text_field :definition
  .field
    = f.label :example
    = f.text_area :example
  .actions
    = f.submit 'Save'

- content_for :page_specific_scripts do
  = javascript_include_tag "card_form"

app/views/cards/edit.html.haml
%h1 Editing card

= render 'form'

= link_to 'Show', @card
\|
= link_to 'Back', cards_path

app/views/cards/index.html.haml
%h1 Listing cards
= link_to 'Create New Card', new_card_path

%table
  %tr
    %th Term
    %th Definition
    %th Object type
    %th Example
    %th Return type
    %th Category

  - @cards.each do |card|
    %tr
      %td= card.terms.map(&:term).join(", ")
      %td{ title: card.definition }= card.definition.truncate(20)
      %td= card.object_type
      %td= card.example.html_safe
      %td= card.return_type
      %td= card.category
      %td= link_to 'Show', card
      %td= link_to 'Edit', edit_card_path(card)
      %td= link_to 'Destroy', card, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Create New Card', new_card_path

app/views/cards/new.html.haml
%h1 New card

= render 'form'

= link_to 'Back', cards_path

app/views/cards/show.html.haml
%p
  %b Term:
  = @card.terms.map(&:term).join(", ")
%p
  %b Definition:
  = @card.definition.html_safe
%p
  %b Object type:
  = @card.object_type
%p
  %b Example:
  = @card.example.html_safe
%p
  %b Return type:
  = @card.return_type
%p
  %b Category:
  = @card.category

= link_to 'New Card', new_card_path
\|
= link_to 'Edit', edit_card_path(@card)
\|
= link_to 'Back', cards_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Flashcards</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= yield :page_specific_scripts %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in?  %>
    <%= render 'shared/main_navigation' %>
  <% end %>
  <div class="notifications row">
    <div class="large-12 center-text">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
  </div>

  <div class="row">
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/home.html.haml
.row
  .large-6.columns
    %h3
      Welcome to Ruby Flashcards!
    %h6
    Choose a Class or Module to study it's methods.
  .large-6.columns
    = form_tag(quiz_sessions_path, :method => 'post')do
      = select_tag(:category, options_for_select(@category), :class => "category_select")
      = select_tag(:object_type, options_for_select(@object_type), :class => "options_select")
      = submit_tag "Start my study session!", class: "button"
%hr/

:javascript
  var categoryObjectTypes = {
    Ruby: #{Card.category_object_types("Ruby").to_json}
  };

  $(document).ready( function() {

    function getSelectedCategory() {
      return $(".category_select").val();
    }

    function renderDependentSelect(category) {
      var select = $("#object_type");
      select.empty();
      $.each(categoryObjectTypes[category], function(i, val) {
        select.append('<option value=' + val + '>' + val + '</option>');
      });
    }

    $("#category").on("change", function(){
      renderDependentSelect(getSelectedCategory());
    });

    renderDependentSelect(getSelectedCategory());
  });

app/views/quiz_sessions/show.html.haml
.row
  .large-12.columns.panel
    %h3
      = @card.definition.html_safe

  .large-12.columns
    %h3
      = form_tag(answer_path, :method => 'post')do
        = text_field_tag(:submitted_answer, nil, placeholder: "Enter your answer here" )
        = hidden_field_tag(:card, @card.id)
        = hidden_field_tag(:id, @quiz_session.id)
        .large-3.large-centered.columns.center-text
          = submit_tag "Am I right?", class: "button"
%hr/

app/views/quiz_sessions/unfinished.html.haml
.row
  .large-4.columns
    %h3 Unfinished Quizzes
    - if @unfinished_quizzes.empty?
      %h7 Congrats!
      %p You have no unfinished quizzes.
      %p
        = link_to("Take a quiz now!", root_path, class: "button")
    - else
      - @unfinished_quizzes.each do |quiz|
        %ul.side-nav
          %li
            #{quiz.category}'s #{quiz.object_type} on #{local_display_date(quiz.created_at)}
            %a{ href: quiz_session_path(quiz.id) } Finish the quiz
  .large-8.columns.center-text
    - if @total_quiz_count > 0
      %p You're making progress!
      %p.large-stat #{@finished_percentage}% finished
      .progress-bar
        .progress{style: "width:#{@finished_percentage}%;" }
      %p #{@total_quiz_count - @unfinished_quizzes.count} out of #{@total_quiz_count} quizzes are finished.
      %P #{@unfinished_quizzes.count} left to finish.

app/views/shared/_main_navigation.html.haml
.row.main_navigation
  .large-12.columns
    .nav-bar.right
      %ul.button-group
        - if params[:controller] != 'stats'
          %li
            = link_to("Stats", stats_path, class: "button")
        - if params[:controller] != 'pages'
          %li
            = link_to("Quiz me", root_path, class: "button")
        - if params[:action] != 'unfinished'
          %li
            = link_to("Unfinished Quizes", unfinished_path, class: "button")
        %li
          = link_to("Logout", destroy_user_session_path, :method => :delete, class: "button")
    %h1
      Ruby Flashcards
    %h4 Know your tools.
    %hr/

app/views/stats/index.html.haml
.row
  .large-4.columns
    %h5 Stats
    - if @past_quizzes.empty?
      %h7 You haven't quized yourself yet!
      %p
        = link_to("Quiz Yourself", root_path)

    - @past_quizzes.each do |quiz|
      %ul.side-nav
        %li
          %a{href: "#{ stat_path(quiz.id)}"} #{ quiz.category }'s #{ quiz.object_type }
          on #{ local_display_date(quiz.created_at) }

/ TODO:give overall stats in the empty chunk. Use show as a guide.
/ what you quizzed yourself on/ how many times.

app/views/stats/show.html.haml
.row
  .large-12.columns.center-text
    %p Congrats on taking the time to work on leveling up!
    %p You got #{ @correct } correct out of #{ @question_total}.
    = form_tag(quiz_sessions_path, :method => 'post')do
      = hidden_field_tag(:category, @quiz_session.category)
      = hidden_field_tag(:object_type, @quiz_session.object_type)
      = submit_tag "Quiz yourself on #{ @quiz_session.category }'s #{ @quiz_session.object_type} again?", :class => 'button center-text'
  .large-12.columns.center-text
    %a{ href: stats_path } View all your stats

/ TODO: add a graph to fill out the main body of the site.
/ google graphs or highcharts
/ highchart possibiilities
/ http://www.highcharts.com/demo/line-time-series
/ http://www.highcharts.com/demo/bar-basic
/ http://www.highcharts.com/demo/column-negative
/ http://www.highcharts.com/demo/column-rotated-labels